Project 1: Sensor Data Analyser
(NumPy)
Generate 10,000 simulated sensor readings
(temperature + current + voltage) using
numpy.random. Compute statistics across all
three channels. Apply boolean indexing to
extract anomalies. Save the anomalies to a
separate CSV using only NumPy (savetxt).
Skills: NumPy arrays, vectorisation, boolean
indexing, np.savetxt

In [1]:
import numpy as np

In [2]:
# Cell 2: Set random seed so you get the same "random" numbers every time
np.random.seed(42)

In [4]:
# Cell 3: Generate synthetic sensor data using NumPy
n_samples = 10000

# Generate temperature readings (normal distribution: mean=50°C, std=15°C)
temperature = np.random.normal(loc=50, scale=15, size=n_samples)

# Generate current readings (mean=5A, std=2A)
current = np.random.normal(loc=5, scale=2, size=n_samples)

# Generate voltage readings (mean=225V, std=5V)
voltage = np.random.normal(loc=225, scale=5, size=n_samples)

print(f"📊 Generated {n_samples:,} readings for each sensor")
print(f"   Temperature shape: {temperature.shape}")
print(f"   Current shape: {current.shape}")
print(f"   Voltage shape: {voltage.shape}")

📊 Generated 10,000 readings for each sensor
   Temperature shape: (10000,)
   Current shape: (10000,)
   Voltage shape: (10000,)


In [9]:
# Cell 4: Look at first 10 readings
print("First 10 readings:")
print("-" * 50)
print(f"{'Index':<8} {'Temp(°C)':<12} {'Current(A)':<12} {'Voltage(V)':<12}")
print("-" * 50)

for i in range(10):
    print(f"{i:<8} {temperature[i]:<12.2f} {current[i]:<12.2f} {voltage[i]:<12.2f}")

First 10 readings:
--------------------------------------------------
Index    Temp(°C)     Current(A)   Voltage(V)  
--------------------------------------------------
0        20.29        4.06         225.49      
1        34.18        7.03         224.68      
2        41.19        4.60         229.76      
3        52.25        5.18         232.66      
4        65.36        6.43         228.43      
5        60.41        4.88         230.06      
6        32.31        1.36         223.91      
7        44.42        7.08         225.63      
8        51.15        7.51         232.43      
9        46.07        1.34         227.63      


In [10]:
# Cell 5: Calculate statistical summaries
def compute_stats(data, name):
    """Calculate and display statistics for a data array"""
    print(f"\n📈 {name} STATISTICS:")
    print(f"   Mean:     {np.mean(data):.2f}")
    print(f"   Median:   {np.median(data):.2f}")
    print(f"   Std Dev:  {np.std(data):.2f}")
    print(f"   Min:      {np.min(data):.2f}")
    print(f"   Max:      {np.max(data):.2f}")
    print(f"   25th %ile:{np.percentile(data, 25):.2f}")
    print(f"   75th %ile:{np.percentile(data, 75):.2f}")
    return {
        'mean': np.mean(data),
        'std': np.std(data),
        'min': np.min(data),
        'max': np.max(data)
    }

# Calculate stats for each sensor
temp_stats = compute_stats(temperature, "TEMPERATURE")
current_stats = compute_stats(current, "CURRENT")
voltage_stats = compute_stats(voltage, "VOLTAGE")


📈 TEMPERATURE STATISTICS:
   Mean:     49.89
   Median:   49.84
   Std Dev:  15.07
   Min:      -16.98
   Max:      105.92
   25th %ile:39.58
   75th %ile:60.19

📈 CURRENT STATISTICS:
   Mean:     5.01
   Median:   5.02
   Std Dev:  2.00
   Min:      -3.59
   Max:      12.07
   25th %ile:3.67
   75th %ile:6.37

📈 VOLTAGE STATISTICS:
   Mean:     225.01
   Median:   225.04
   Std Dev:  5.05
   Min:      204.21
   Max:      243.73
   25th %ile:221.62
   75th %ile:228.45


In [11]:
# Cell 6: Define anomaly boundaries (mean ± 2 standard deviations)
# This captures ~95% of normal data; anything outside is an anomaly

# Temperature anomalies: outside [mean-2*std, mean+2*std]
temp_lower = temp_stats['mean'] - 2 * temp_stats['std']
temp_upper = temp_stats['mean'] + 2 * temp_stats['std']

# Current anomalies
current_lower = current_stats['mean'] - 2 * current_stats['std']
current_upper = current_stats['mean'] + 2 * current_stats['std']

# Voltage anomalies
voltage_lower = voltage_stats['mean'] - 2 * voltage_stats['std']
voltage_upper = voltage_stats['mean'] + 2 * voltage_stats['std']

print("🔍 ANOMALY THRESHOLDS (mean ± 2σ):")
print(f"   Temperature: {temp_lower:.2f}°C to {temp_upper:.2f}°C")
print(f"   Current:     {current_lower:.2f}A to {current_upper:.2f}A")
print(f"   Voltage:     {voltage_lower:.2f}V to {voltage_upper:.2f}V")

🔍 ANOMALY THRESHOLDS (mean ± 2σ):
   Temperature: 19.75°C to 80.02°C
   Current:     1.01A to 9.01A
   Voltage:     214.91V to 235.11V


In [13]:
# Cell 7: Use boolean indexing to find anomalous readings

# Create boolean masks (True where anomaly occurs)
temp_anomaly_mask = (temperature < temp_lower) | (temperature > temp_upper)
current_anomaly_mask = (current < current_lower) | (current > current_upper)
voltage_anomaly_mask = (voltage < voltage_lower) | (voltage > voltage_upper)

# Combined mask: ANY sensor has anomaly
combined_mask = temp_anomaly_mask | current_anomaly_mask | voltage_anomaly_mask

# Count anomalies
temp_anomaly_count = np.sum(temp_anomaly_mask)
current_anomaly_count = np.sum(current_anomaly_mask)
voltage_anomaly_count = np.sum(voltage_anomaly_mask)
combined_count = np.sum(combined_mask)

print("🔴 ANOMALY DETECTION RESULTS:")
print(f"   Temperature anomalies: {temp_anomaly_count}/{n_samples} ({temp_anomaly_count/n_samples*100:.1f}%)")
print(f"   Current anomalies:     {current_anomaly_count}/{n_samples} ({current_anomaly_count/n_samples*100:.1f}%)")
print(f"   Voltage anomalies:     {voltage_anomaly_count}/{n_samples} ({voltage_anomaly_count/n_samples*100:.1f}%)")
print(f"   Rows with ANY anomaly: {combined_count}/{n_samples} ({combined_count/n_samples*100:.1f}%)")

🔴 ANOMALY DETECTION RESULTS:
   Temperature anomalies: 451/10000 (4.5%)
   Current anomalies:     456/10000 (4.6%)
   Voltage anomalies:     456/10000 (4.6%)
   Rows with ANY anomaly: 1296/10000 (13.0%)


In [14]:
# Cell 8: Extract only the anomalous readings using boolean indexing

# Extract all three channels for rows where ANY anomaly occurred
anomaly_temps = temperature[combined_mask]
anomaly_currents = current[combined_mask]
anomaly_voltages = voltage[combined_mask]

# Also get indices of anomalies (useful for tracking)
anomaly_indices = np.where(combined_mask)[0]

print(f"📋 Extracted {len(anomaly_temps)} anomalous readings")
print("\nFirst 10 anomalies:")
print("-" * 65)
print(f"{'Index':<8} {'Temp(°C)':<12} {'Current(A)':<12} {'Voltage(V)':<12} {'Reason':<15}")
print("-" * 65)

for i in range(min(10, len(anomaly_indices))):
    idx = anomaly_indices[i]
    reasons = []
    if temp_anomaly_mask[idx]:
        reasons.append("Temp")
    if current_anomaly_mask[idx]:
        reasons.append("Current")
    if voltage_anomaly_mask[idx]:
        reasons.append("Voltage")
    reason_str = ", ".join(reasons)
    
    print(f"{idx:<8} {temperature[idx]:<12.2f} {current[idx]:<12.2f} {voltage[idx]:<12.2f} {reason_str:<15}")

📋 Extracted 1296 anomalous readings

First 10 anomalies:
-----------------------------------------------------------------
Index    Temp(°C)     Current(A)   Voltage(V)   Reason         
-----------------------------------------------------------------
11       24.16        9.05         225.16       Current        
14       3.60         4.15         220.79       Temp           
27       14.17        4.32         221.20       Temp           
40       59.30        1.94         237.53       Voltage        
42       37.74        10.08        217.56       Current        
49       50.74        9.39         236.31       Current, Voltage
50       38.48        10.24        216.82       Current        
53       17.84        6.85         221.55       Temp           
68       84.28        5.03         218.90       Temp           
77       69.22        10.30        226.08       Current        


In [15]:
# Cell 9: Save anomalies to CSV file using np.savetxt (no pandas!)

# Stack arrays into columns (column 0=index, 1=temp, 2=current, 3=voltage)
anomaly_data = np.column_stack([
    anomaly_indices,      # Original reading index
    anomaly_temps,        # Temperature values
    anomaly_currents,     # Current values
    anomaly_voltages      # Voltage values
])

# Add header line
header = "Reading_ID,Temperature_C,Current_A,Voltage_V"

# Save to CSV file
np.savetxt("anomalies.csv", anomaly_data, 
           delimiter=",", 
           header=header, 
           comments="",      # Remove default '#' from header
           fmt=['%d', '%.2f', '%.2f', '%.2f'])  # Format: integer, 2 decimal floats

print("💾 Anomalies saved to 'anomalies.csv'")
print(f"   File contains {len(anomaly_data)} rows × 4 columns")

💾 Anomalies saved to 'anomalies.csv'
   File contains 1296 rows × 4 columns


In [16]:
# Cell 10: Read back and verify (using NumPy only)
loaded_data = np.loadtxt("anomalies.csv", delimiter=",", skiprows=1)
print("✅ Verification: Successfully read back from CSV")
print(f"   Loaded shape: {loaded_data.shape}")
print(f"   First 5 rows:\n{loaded_data[:5]}")

✅ Verification: Successfully read back from CSV
   Loaded shape: (1296, 4)
   First 5 rows:
[[ 11.    24.16   9.05 225.16]
 [ 14.     3.6    4.15 220.79]
 [ 27.    14.17   4.32 221.2 ]
 [ 40.    59.3    1.94 237.53]
 [ 42.    37.74  10.08 217.56]]
